<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>TiltedControls.WinUI.Desktop</RootNamespace>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <UseWinUI>true</UseWinUI>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
      <PackageReference Include="CommunityToolkit.WinUI.Animations" Version="8.2.251219" />
      <PackageReference Include="CommunityToolkit.WinUI.Extensions" Version="8.2.251219" />
      <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.3.2-experimentalA" />
      <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.2526" />
  </ItemGroup>

  <Import Project="..\TiltedControls.Shared\TiltedControls.Shared.projitems" Label="Shared" />
</Project>
